### ISSUE TITLE
[Typo] cppregex: import -> #include

### ISSUE THREAD

**Issue by Cycatz** [ayaka14732/ayaka-site#2] opened 2022-01-11 05:10 UTC
In the article [cppregex](https://ayaka.shn.hk/cppregex/), all `#include` lines in the example code were written as `import`.

**Comment by ayaka14732** [comment] 2022-01-11 05:50
`import` is also correct

**Comment by ayaka14732** [comment] 2022-01-11 06:00
As this is a feature, not a bug, I am going to close this issue for now.

**Closed as completed by ayaka14732** 2022-01-11 06:00 UTC

**Comment by Cycatz** [comment] 2022-01-11 06:25
Oh cool! I really don't know this feature!
